apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accounts
    
    spec:
      template:
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/sn-labs-paixela93/accounts:1
            name: accounts